### ISSUE TITLE
Provide example JS/Node command-line application

### ISSUE THREAD

**Issue by christophgockel** [vanilla-project/vanilla-project.github.io#14]
Similar to the [Ruby Command Line Application guide](https://vanilla-project.guide/ruby/command-line) we should have an example repository for the JS/Node guide.

**Comment by nickbdyer** [comment]
On it

**Comment by christophgockel** [comment]
Awesome!

**Comment by christophgockel** [comment]
This has been addressed and is available at http://localhost:8080/node/command-line/ and https://github.com/vanilla-project/node-command-line respectively.

Thank you @nickbdyer !
